### ISSUE TITLE
Inconsistency in fi_index

### ISSUE THREAD

**Issue by Behroosh** [DependableSystemsLab/LLFI#86]
The fi_index starts from 1 in the PROGRAM-faultinjection.ll and PROGRAM-llfi_index. However, the fi_index is counted from zero in files such as llfi.stat.trace.prof (golden run), llfi.stat.trace (fault injection run) and llfi.stat.fi.injectedfaults. This causes some inconsistency in the trace files and the instructions that have actually been targeted.

**Comment by nankmr2012** [comment]
The issue was resolved by troubling shooting thr llvm_pass directory for index generating file (Utils.cpp), where one of the variable(fi_index) initial point was changed to one from zero.
The same is corrected in gui directory in the instrument phase file (InstrumentController). Now the index for instruction starts one in all the file and matches. The regression test was conducted after implementing changes and found pass.

**Comment by abrahamchan** [comment]
I have successfully reviewed this fix with Nanda.
